package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CCondicionventaCr generated by hbm2java
 */
public class CCondicionventaCr  implements java.io.Serializable {


     private Integer idCondicionVenta;
     private String CCondicionVenta;
     private String descripcion;
     private Date fechaInicioV;
     private Date fechaFinalV;

    public CCondicionventaCr() {
    }

    public CCondicionventaCr(String CCondicionVenta, String descripcion, Date fechaInicioV, Date fechaFinalV) {
       this.CCondicionVenta = CCondicionVenta;
       this.descripcion = descripcion;
       this.fechaInicioV = fechaInicioV;
       this.fechaFinalV = fechaFinalV;
    }
   
    public Integer getIdCondicionVenta() {
        return this.idCondicionVenta;
    }
    
    public void setIdCondicionVenta(Integer idCondicionVenta) {
        this.idCondicionVenta = idCondicionVenta;
    }
    public String getCCondicionVenta() {
        return this.CCondicionVenta;
    }
    
    public void setCCondicionVenta(String CCondicionVenta) {
        this.CCondicionVenta = CCondicionVenta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicioV() {
        return this.fechaInicioV;
    }
    
    public void setFechaInicioV(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public Date getFechaFinalV() {
        return this.fechaFinalV;
    }
    
    public void setFechaFinalV(Date fechaFinalV) {
        this.fechaFinalV = fechaFinalV;
    }




}


