package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private Empresas empresas;
     private String nombre;
     private String rfc;
     private String identificador;
     private Boolean requiereAddenda;
     private Boolean requiereEdifact;
     private String calle;
     private String numExterior;
     private String numInterior;
     private String colonia;
     private String localidad;
     private String referencia;
     private String municipio;
     private String estado;
     private String pais;
     private String cp;
     private Boolean requiereAperak;
     private Boolean requiereContrl;
     private String codigogln;
     private String modoEnvio;
     private String alias;
     private String contacto;
     private String emailContacto;
     private String condicionesPago;
     private Byte esFrontera;
     private String telefono;
     private String residenciaFiscal;
     private String numRegIdTrib;
     private Set cfdses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(Empresas empresas, String rfc, String modoEnvio) {
        this.empresas = empresas;
        this.rfc = rfc;
        this.modoEnvio = modoEnvio;
    }
    public Clientes(Empresas empresas, String nombre, String rfc, String identificador, Boolean requiereAddenda, Boolean requiereEdifact, String calle, String numExterior, String numInterior, String colonia, String localidad, String referencia, String municipio, String estado, String pais, String cp, Boolean requiereAperak, Boolean requiereContrl, String codigogln, String modoEnvio, String alias, String contacto, String emailContacto, String condicionesPago, Byte esFrontera, String telefono, String residenciaFiscal, String numRegIdTrib, Set cfdses) {
       this.empresas = empresas;
       this.nombre = nombre;
       this.rfc = rfc;
       this.identificador = identificador;
       this.requiereAddenda = requiereAddenda;
       this.requiereEdifact = requiereEdifact;
       this.calle = calle;
       this.numExterior = numExterior;
       this.numInterior = numInterior;
       this.colonia = colonia;
       this.localidad = localidad;
       this.referencia = referencia;
       this.municipio = municipio;
       this.estado = estado;
       this.pais = pais;
       this.cp = cp;
       this.requiereAperak = requiereAperak;
       this.requiereContrl = requiereContrl;
       this.codigogln = codigogln;
       this.modoEnvio = modoEnvio;
       this.alias = alias;
       this.contacto = contacto;
       this.emailContacto = emailContacto;
       this.condicionesPago = condicionesPago;
       this.esFrontera = esFrontera;
       this.telefono = telefono;
       this.residenciaFiscal = residenciaFiscal;
       this.numRegIdTrib = numRegIdTrib;
       this.cfdses = cfdses;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public Boolean getRequiereAddenda() {
        return this.requiereAddenda;
    }
    
    public void setRequiereAddenda(Boolean requiereAddenda) {
        this.requiereAddenda = requiereAddenda;
    }
    public Boolean getRequiereEdifact() {
        return this.requiereEdifact;
    }
    
    public void setRequiereEdifact(Boolean requiereEdifact) {
        this.requiereEdifact = requiereEdifact;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumExterior() {
        return this.numExterior;
    }
    
    public void setNumExterior(String numExterior) {
        this.numExterior = numExterior;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Boolean getRequiereAperak() {
        return this.requiereAperak;
    }
    
    public void setRequiereAperak(Boolean requiereAperak) {
        this.requiereAperak = requiereAperak;
    }
    public Boolean getRequiereContrl() {
        return this.requiereContrl;
    }
    
    public void setRequiereContrl(Boolean requiereContrl) {
        this.requiereContrl = requiereContrl;
    }
    public String getCodigogln() {
        return this.codigogln;
    }
    
    public void setCodigogln(String codigogln) {
        this.codigogln = codigogln;
    }
    public String getModoEnvio() {
        return this.modoEnvio;
    }
    
    public void setModoEnvio(String modoEnvio) {
        this.modoEnvio = modoEnvio;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmailContacto() {
        return this.emailContacto;
    }
    
    public void setEmailContacto(String emailContacto) {
        this.emailContacto = emailContacto;
    }
    public String getCondicionesPago() {
        return this.condicionesPago;
    }
    
    public void setCondicionesPago(String condicionesPago) {
        this.condicionesPago = condicionesPago;
    }
    public Byte getEsFrontera() {
        return this.esFrontera;
    }
    
    public void setEsFrontera(Byte esFrontera) {
        this.esFrontera = esFrontera;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getResidenciaFiscal() {
        return this.residenciaFiscal;
    }
    
    public void setResidenciaFiscal(String residenciaFiscal) {
        this.residenciaFiscal = residenciaFiscal;
    }
    public String getNumRegIdTrib() {
        return this.numRegIdTrib;
    }
    
    public void setNumRegIdTrib(String numRegIdTrib) {
        this.numRegIdTrib = numRegIdTrib;
    }
    public Set getCfdses() {
        return this.cfdses;
    }
    
    public void setCfdses(Set cfdses) {
        this.cfdses = cfdses;
    }




}


