package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CMonedaCr generated by hbm2java
 */
public class CMonedaCr  implements java.io.Serializable {


     private Integer idMoneda;
     private String CMoneda;
     private String descripcion;
     private String decimales;
     private Date fechaInicioV;
     private Date fechaFinV;

    public CMonedaCr() {
    }

	
    public CMonedaCr(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public CMonedaCr(String CMoneda, String descripcion, String decimales, Date fechaInicioV, Date fechaFinV) {
       this.CMoneda = CMoneda;
       this.descripcion = descripcion;
       this.decimales = decimales;
       this.fechaInicioV = fechaInicioV;
       this.fechaFinV = fechaFinV;
    }
   
    public Integer getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(Integer idMoneda) {
        this.idMoneda = idMoneda;
    }
    public String getCMoneda() {
        return this.CMoneda;
    }
    
    public void setCMoneda(String CMoneda) {
        this.CMoneda = CMoneda;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDecimales() {
        return this.decimales;
    }
    
    public void setDecimales(String decimales) {
        this.decimales = decimales;
    }
    public Date getFechaInicioV() {
        return this.fechaInicioV;
    }
    
    public void setFechaInicioV(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public Date getFechaFinV() {
        return this.fechaFinV;
    }
    
    public void setFechaFinV(Date fechaFinV) {
        this.fechaFinV = fechaFinV;
    }




}


