package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1



/**
 * ConfiguracionesEmpresas generated by hbm2java
 */
public class ConfiguracionesEmpresas  implements java.io.Serializable {


     private Integer idConfiguracion;
     private Empresas empresas;
     private String propiedad;
     private String valor;
     private String tipo;
     private String descripcion;
     private Boolean visible;
     private String tipoValor;
     private Boolean requerido;

    public ConfiguracionesEmpresas() {
    }

	
    public ConfiguracionesEmpresas(Empresas empresas, String propiedad, String tipoValor) {
        this.empresas = empresas;
        this.propiedad = propiedad;
        this.tipoValor = tipoValor;
    }
    public ConfiguracionesEmpresas(Empresas empresas, String propiedad, String valor, String tipo, String descripcion, Boolean visible, String tipoValor, Boolean requerido) {
       this.empresas = empresas;
       this.propiedad = propiedad;
       this.valor = valor;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.visible = visible;
       this.tipoValor = tipoValor;
       this.requerido = requerido;
    }
   
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getPropiedad() {
        return this.propiedad;
    }
    
    public void setPropiedad(String propiedad) {
        this.propiedad = propiedad;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public String getTipoValor() {
        return this.tipoValor;
    }
    
    public void setTipoValor(String tipoValor) {
        this.tipoValor = tipoValor;
    }
    public Boolean getRequerido() {
        return this.requerido;
    }
    
    public void setRequerido(Boolean requerido) {
        this.requerido = requerido;
    }




}


