package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CTipoidentificacionCr generated by hbm2java
 */
public class CTipoidentificacionCr  implements java.io.Serializable {


     private Integer idTipoIdentificacion;
     private String CTipoIdentificacion;
     private String descripcion;
     private Date fechaInicioV;
     private Date fechaFinV;

    public CTipoidentificacionCr() {
    }

	
    public CTipoidentificacionCr(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public CTipoidentificacionCr(String CTipoIdentificacion, String descripcion, Date fechaInicioV, Date fechaFinV) {
       this.CTipoIdentificacion = CTipoIdentificacion;
       this.descripcion = descripcion;
       this.fechaInicioV = fechaInicioV;
       this.fechaFinV = fechaFinV;
    }
   
    public Integer getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(Integer idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getCTipoIdentificacion() {
        return this.CTipoIdentificacion;
    }
    
    public void setCTipoIdentificacion(String CTipoIdentificacion) {
        this.CTipoIdentificacion = CTipoIdentificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicioV() {
        return this.fechaInicioV;
    }
    
    public void setFechaInicioV(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public Date getFechaFinV() {
        return this.fechaFinV;
    }
    
    public void setFechaFinV(Date fechaFinV) {
        this.fechaFinV = fechaFinV;
    }




}


