package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DocumentosRecibidos generated by hbm2java
 */
public class DocumentosRecibidos  implements java.io.Serializable {


     private Integer idArchivo;
     private CTipodocumentoCr CTipodocumentoCr;
     private Sucursales sucursales;
     private Integer idCfd;
     private Date fechaRecepcion;
     private String archivo;
     private String clave;
     private String estado;
     private String tipo;
     private String nombre;
     private String error;
     private Xmls xmls;

    public DocumentosRecibidos() {
    }

	
    public DocumentosRecibidos(Sucursales sucursales, Date fechaRecepcion, String archivo, String clave, String estado) {
        this.sucursales = sucursales;
        this.fechaRecepcion = fechaRecepcion;
        this.archivo = archivo;
        this.clave = clave;
        this.estado = estado;
    }
    public DocumentosRecibidos(CTipodocumentoCr CTipodocumentoCr, Sucursales sucursales, Integer idCfd, Date fechaRecepcion, String archivo, String clave, String estado, String tipo, String nombre, String error, Xmls xmls) {
       this.CTipodocumentoCr = CTipodocumentoCr;
       this.sucursales = sucursales;
       this.idCfd = idCfd;
       this.fechaRecepcion = fechaRecepcion;
       this.archivo = archivo;
       this.clave = clave;
       this.estado = estado;
       this.tipo = tipo;
       this.nombre = nombre;
       this.error = error;
       this.xmls = xmls;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public CTipodocumentoCr getCTipodocumentoCr() {
        return this.CTipodocumentoCr;
    }
    
    public void setCTipodocumentoCr(CTipodocumentoCr CTipodocumentoCr) {
        this.CTipodocumentoCr = CTipodocumentoCr;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Integer getIdCfd() {
        return this.idCfd;
    }
    
    public void setIdCfd(Integer idCfd) {
        this.idCfd = idCfd;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public Xmls getXmls() {
        return this.xmls;
    }
    
    public void setXmls(Xmls xmls) {
        this.xmls = xmls;
    }




}


