package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private String status;
     private String keyEmpresa;
     private String email;
     private String nombreArchivoLogo;
     private String nombreContacto;
     private String idTipo;
     private String idNumero;
     private String provincia;
     private String canton;
     private String distrito;
     private String otrasSenias;
     private String telefonoCodpais;
     private String numTelefono;
     private Set configuracionesTokens = new HashSet(0);
     private Set configuracionPlantillas = new HashSet(0);
     private Set sucursaleses = new HashSet(0);
     private Set clienteses = new HashSet(0);
     private Set configuracionesEmpresases = new HashSet(0);
     private Set tokens = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String nombre, String status, String idTipo, String idNumero, String provincia, String canton, String distrito, String telefonoCodpais, String numTelefono) {
        this.nombre = nombre;
        this.status = status;
        this.idTipo = idTipo;
        this.idNumero = idNumero;
        this.provincia = provincia;
        this.canton = canton;
        this.distrito = distrito;
        this.telefonoCodpais = telefonoCodpais;
        this.numTelefono = numTelefono;
    }
    public Empresas(String nombre, String status, String keyEmpresa, String email, String nombreArchivoLogo, String nombreContacto, String idTipo, String idNumero, String provincia, String canton, String distrito, String otrasSenias, String telefonoCodpais, String numTelefono, Set configuracionesTokens, Set configuracionPlantillas, Set sucursaleses, Set clienteses, Set configuracionesEmpresases, Set tokens) {
       this.nombre = nombre;
       this.status = status;
       this.keyEmpresa = keyEmpresa;
       this.email = email;
       this.nombreArchivoLogo = nombreArchivoLogo;
       this.nombreContacto = nombreContacto;
       this.idTipo = idTipo;
       this.idNumero = idNumero;
       this.provincia = provincia;
       this.canton = canton;
       this.distrito = distrito;
       this.otrasSenias = otrasSenias;
       this.telefonoCodpais = telefonoCodpais;
       this.numTelefono = numTelefono;
       this.configuracionesTokens = configuracionesTokens;
       this.configuracionPlantillas = configuracionPlantillas;
       this.sucursaleses = sucursaleses;
       this.clienteses = clienteses;
       this.configuracionesEmpresases = configuracionesEmpresases;
       this.tokens = tokens;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getKeyEmpresa() {
        return this.keyEmpresa;
    }
    
    public void setKeyEmpresa(String keyEmpresa) {
        this.keyEmpresa = keyEmpresa;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombreArchivoLogo() {
        return this.nombreArchivoLogo;
    }
    
    public void setNombreArchivoLogo(String nombreArchivoLogo) {
        this.nombreArchivoLogo = nombreArchivoLogo;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(String idTipo) {
        this.idTipo = idTipo;
    }
    public String getIdNumero() {
        return this.idNumero;
    }
    
    public void setIdNumero(String idNumero) {
        this.idNumero = idNumero;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public String getOtrasSenias() {
        return this.otrasSenias;
    }
    
    public void setOtrasSenias(String otrasSenias) {
        this.otrasSenias = otrasSenias;
    }
    public String getTelefonoCodpais() {
        return this.telefonoCodpais;
    }
    
    public void setTelefonoCodpais(String telefonoCodpais) {
        this.telefonoCodpais = telefonoCodpais;
    }
    public String getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }
    public Set getConfiguracionesTokens() {
        return this.configuracionesTokens;
    }
    
    public void setConfiguracionesTokens(Set configuracionesTokens) {
        this.configuracionesTokens = configuracionesTokens;
    }
    public Set getConfiguracionPlantillas() {
        return this.configuracionPlantillas;
    }
    
    public void setConfiguracionPlantillas(Set configuracionPlantillas) {
        this.configuracionPlantillas = configuracionPlantillas;
    }
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getConfiguracionesEmpresases() {
        return this.configuracionesEmpresases;
    }
    
    public void setConfiguracionesEmpresases(Set configuracionesEmpresases) {
        this.configuracionesEmpresases = configuracionesEmpresases;
    }
    public Set getTokens() {
        return this.tokens;
    }
    
    public void setTokens(Set tokens) {
        this.tokens = tokens;
    }




}


