package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Opciones generated by hbm2java
 */
public class Opciones  implements java.io.Serializable {


     private Integer idOpcion;
     private Integer idGrupo;
     private String opcion;
     private String href;
     private Short orden;
     private Boolean visible;
     private String descripcion;
     private String nivel;
     private Integer idModulo;
     private Integer opcionesIdOpcion;
     private String identificador;
     private String tipo;
     private String icono;
     private Set roleses = new HashSet(0);

    public Opciones() {
    }

	
    public Opciones(String opcion) {
        this.opcion = opcion;
    }
    public Opciones(Integer idGrupo, String opcion, String href, Short orden, Boolean visible, String descripcion, String nivel, Integer idModulo, Integer opcionesIdOpcion, String identificador, String tipo, String icono, Set roleses) {
       this.idGrupo = idGrupo;
       this.opcion = opcion;
       this.href = href;
       this.orden = orden;
       this.visible = visible;
       this.descripcion = descripcion;
       this.nivel = nivel;
       this.idModulo = idModulo;
       this.opcionesIdOpcion = opcionesIdOpcion;
       this.identificador = identificador;
       this.tipo = tipo;
       this.icono = icono;
       this.roleses = roleses;
    }
   
    public Integer getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    public String getHref() {
        return this.href;
    }
    
    public void setHref(String href) {
        this.href = href;
    }
    public Short getOrden() {
        return this.orden;
    }
    
    public void setOrden(Short orden) {
        this.orden = orden;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Integer getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(Integer idModulo) {
        this.idModulo = idModulo;
    }
    public Integer getOpcionesIdOpcion() {
        return this.opcionesIdOpcion;
    }
    
    public void setOpcionesIdOpcion(Integer opcionesIdOpcion) {
        this.opcionesIdOpcion = opcionesIdOpcion;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


