package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRol;
     private String nombre;
     private String tipo;
     private String uso;
     private Set opcioneses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String nombre, String tipo, String uso) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.uso = uso;
    }
    public Roles(String nombre, String tipo, String uso, Set opcioneses) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.uso = uso;
       this.opcioneses = opcioneses;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getUso() {
        return this.uso;
    }
    
    public void setUso(String uso) {
        this.uso = uso;
    }
    public Set getOpcioneses() {
        return this.opcioneses;
    }
    
    public void setOpcioneses(Set opcioneses) {
        this.opcioneses = opcioneses;
    }




}


