package com.iqtb.pojos.xsaCR;
// Generated 4/04/2022 02:52:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token  implements java.io.Serializable {


     private Integer idToken;
     private Empresas empresas;
     private String tokenAcceso;
     private String refreshToken;
     private Date fechaPeticion;
     private String sessionState;
     private String tokenType;
     private byte seRefresco;

    public Token() {
    }

    public Token(Empresas empresas, String tokenAcceso, String refreshToken, Date fechaPeticion, String sessionState, String tokenType, byte seRefresco) {
       this.empresas = empresas;
       this.tokenAcceso = tokenAcceso;
       this.refreshToken = refreshToken;
       this.fechaPeticion = fechaPeticion;
       this.sessionState = sessionState;
       this.tokenType = tokenType;
       this.seRefresco = seRefresco;
    }
   
    public Integer getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(Integer idToken) {
        this.idToken = idToken;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getTokenAcceso() {
        return this.tokenAcceso;
    }
    
    public void setTokenAcceso(String tokenAcceso) {
        this.tokenAcceso = tokenAcceso;
    }
    public String getRefreshToken() {
        return this.refreshToken;
    }
    
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }
    public Date getFechaPeticion() {
        return this.fechaPeticion;
    }
    
    public void setFechaPeticion(Date fechaPeticion) {
        this.fechaPeticion = fechaPeticion;
    }
    public String getSessionState() {
        return this.sessionState;
    }
    
    public void setSessionState(String sessionState) {
        this.sessionState = sessionState;
    }
    public String getTokenType() {
        return this.tokenType;
    }
    
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }
    public byte getSeRefresco() {
        return this.seRefresco;
    }
    
    public void setSeRefresco(byte seRefresco) {
        this.seRefresco = seRefresco;
    }




}


