package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CMediopagoCr generated by hbm2java
 */
public class CMediopagoCr  implements java.io.Serializable {


     private Integer idMedioPago;
     private String CMedioPago;
     private String descripcion;
     private Date fechaInicioV;
     private Date fechaFinalV;

    public CMediopagoCr() {
    }

    public CMediopagoCr(String CMedioPago, String descripcion, Date fechaInicioV, Date fechaFinalV) {
       this.CMedioPago = CMedioPago;
       this.descripcion = descripcion;
       this.fechaInicioV = fechaInicioV;
       this.fechaFinalV = fechaFinalV;
    }
   
    public Integer getIdMedioPago() {
        return this.idMedioPago;
    }
    
    public void setIdMedioPago(Integer idMedioPago) {
        this.idMedioPago = idMedioPago;
    }
    public String getCMedioPago() {
        return this.CMedioPago;
    }
    
    public void setCMedioPago(String CMedioPago) {
        this.CMedioPago = CMedioPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicioV() {
        return this.fechaInicioV;
    }
    
    public void setFechaInicioV(Date fechaInicioV) {
        this.fechaInicioV = fechaInicioV;
    }
    public Date getFechaFinalV() {
        return this.fechaFinalV;
    }
    
    public void setFechaFinalV(Date fechaFinalV) {
        this.fechaFinalV = fechaFinalV;
    }




}


