package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * ConectorAdaptador generated by hbm2java
 */
public class ConectorAdaptador  implements java.io.Serializable {


     private Integer idConectorAdaptador;
     private Empresas empresas;
     private String nombre;
     private String descripcion;
     private String stylusConector;
     private String xsltToTralix;
     private String estado;

    public ConectorAdaptador() {
    }

	
    public ConectorAdaptador(Empresas empresas, String nombre) {
        this.empresas = empresas;
        this.nombre = nombre;
    }
    public ConectorAdaptador(Empresas empresas, String nombre, String descripcion, String stylusConector, String xsltToTralix, String estado) {
       this.empresas = empresas;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stylusConector = stylusConector;
       this.xsltToTralix = xsltToTralix;
       this.estado = estado;
    }
   
    public Integer getIdConectorAdaptador() {
        return this.idConectorAdaptador;
    }
    
    public void setIdConectorAdaptador(Integer idConectorAdaptador) {
        this.idConectorAdaptador = idConectorAdaptador;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getStylusConector() {
        return this.stylusConector;
    }
    
    public void setStylusConector(String stylusConector) {
        this.stylusConector = stylusConector;
    }
    public String getXsltToTralix() {
        return this.xsltToTralix;
    }
    
    public void setXsltToTralix(String xsltToTralix) {
        this.xsltToTralix = xsltToTralix;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


