package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * ConfiguracionesParametros generated by hbm2java
 */
public class ConfiguracionesParametros  implements java.io.Serializable {


     private Integer idConfiguracionParametro;
     private Sucursales sucursales;
     private String propiedad;
     private String valor;

    public ConfiguracionesParametros() {
    }

	
    public ConfiguracionesParametros(Sucursales sucursales, String propiedad) {
        this.sucursales = sucursales;
        this.propiedad = propiedad;
    }
    public ConfiguracionesParametros(Sucursales sucursales, String propiedad, String valor) {
       this.sucursales = sucursales;
       this.propiedad = propiedad;
       this.valor = valor;
    }
   
    public Integer getIdConfiguracionParametro() {
        return this.idConfiguracionParametro;
    }
    
    public void setIdConfiguracionParametro(Integer idConfiguracionParametro) {
        this.idConfiguracionParametro = idConfiguracionParametro;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getPropiedad() {
        return this.propiedad;
    }
    
    public void setPropiedad(String propiedad) {
        this.propiedad = propiedad;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


