package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * ConfiguracionesToken generated by hbm2java
 */
public class ConfiguracionesToken  implements java.io.Serializable {


     private Integer idConfigToken;
     private Empresas empresas;
     private boolean urlProdPrue;
     private String user;
     private String password;

    public ConfiguracionesToken() {
    }

    public ConfiguracionesToken(Empresas empresas, boolean urlProdPrue, String user, String password) {
       this.empresas = empresas;
       this.urlProdPrue = urlProdPrue;
       this.user = user;
       this.password = password;
    }
   
    public Integer getIdConfigToken() {
        return this.idConfigToken;
    }
    
    public void setIdConfigToken(Integer idConfigToken) {
        this.idConfigToken = idConfigToken;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public boolean isUrlProdPrue() {
        return this.urlProdPrue;
    }
    
    public void setUrlProdPrue(boolean urlProdPrue) {
        this.urlProdPrue = urlProdPrue;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


