package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentosRecibidos generated by hbm2java
 */
public class DocumentosRecibidos  implements java.io.Serializable {


     private Integer idArchivo;
     private Cfds cfds;
     private Sucursales sucursales;
     private TiposCfd tiposCfd;
     private Date fechaRecepcion;
     private String archivo;
     private String clave;
     private String estado;
     private String tipo;
     private String nombre;
     private String error;
     private Set xmlses = new HashSet(0);

    public DocumentosRecibidos() {
    }

	
    public DocumentosRecibidos(Sucursales sucursales, TiposCfd tiposCfd, Date fechaRecepcion, String archivo, String estado) {
        this.sucursales = sucursales;
        this.tiposCfd = tiposCfd;
        this.fechaRecepcion = fechaRecepcion;
        this.archivo = archivo;
        this.estado = estado;
    }
    public DocumentosRecibidos(Cfds cfds, Sucursales sucursales, TiposCfd tiposCfd, Date fechaRecepcion, String archivo, String clave, String estado, String tipo, String nombre, String error, Set xmlses) {
       this.cfds = cfds;
       this.sucursales = sucursales;
       this.tiposCfd = tiposCfd;
       this.fechaRecepcion = fechaRecepcion;
       this.archivo = archivo;
       this.clave = clave;
       this.estado = estado;
       this.tipo = tipo;
       this.nombre = nombre;
       this.error = error;
       this.xmlses = xmlses;
    }
    
    public DocumentosRecibidos(Sucursales sucursales, TiposCfd tiposCfd, Date fechaRecepcion, String archivo){
    
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Cfds getCfds() {
        return this.cfds;
    }
    
    public void setCfds(Cfds cfds) {
        this.cfds = cfds;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public Set getXmlses() {
        return this.xmlses;
    }
    
    public void setXmlses(Set xmlses) {
        this.xmlses = xmlses;
    }




}


