package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private Integer idGrupo;
     private String grupo;
     private Short orden;
     private Set opcioneses = new HashSet(0);

    public Grupos() {
    }

    public Grupos(String grupo, Short orden, Set opcioneses) {
       this.grupo = grupo;
       this.orden = orden;
       this.opcioneses = opcioneses;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Short getOrden() {
        return this.orden;
    }
    
    public void setOrden(Short orden) {
        this.orden = orden;
    }
    public Set getOpcioneses() {
        return this.opcioneses;
    }
    
    public void setOpcioneses(Set opcioneses) {
        this.opcioneses = opcioneses;
    }




}


