package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulos generated by hbm2java
 */
public class Modulos  implements java.io.Serializable {


     private int idModulo;
     private String nombre;
     private String descripcion;
     private boolean visible;
     private boolean activo;
     private Set opcioneses = new HashSet(0);

    public Modulos() {
    }

	
    public Modulos(int idModulo, String nombre, boolean visible, boolean activo) {
        this.idModulo = idModulo;
        this.nombre = nombre;
        this.visible = visible;
        this.activo = activo;
    }
    public Modulos(int idModulo, String nombre, String descripcion, boolean visible, boolean activo, Set opcioneses) {
       this.idModulo = idModulo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.visible = visible;
       this.activo = activo;
       this.opcioneses = opcioneses;
    }
   
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getOpcioneses() {
        return this.opcioneses;
    }
    
    public void setOpcioneses(Set opcioneses) {
        this.opcioneses = opcioneses;
    }




}


