package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Opciones generated by hbm2java
 */
public class Opciones  implements java.io.Serializable {


     private Integer idOpcion;
     private Grupos grupos;
     private Modulos modulos;
     private String opcion;
     private String href;
     private Short orden;
     private Boolean visible;
     private String descripcion;
     private String nivel;
     private Integer opcionesIdOpcion;
     private String identificador;
     private String tipo;
     private String icono;
     private Set rolesOpcioneses = new HashSet(0);

    public Opciones() {
    }

	
    public Opciones(String opcion) {
        this.opcion = opcion;
    }
    public Opciones(Grupos grupos, Modulos modulos, String opcion, String href, Short orden, Boolean visible, String descripcion, String nivel, Integer opcionesIdOpcion, String identificador, String tipo, String icono, Set rolesOpcioneses) {
       this.grupos = grupos;
       this.modulos = modulos;
       this.opcion = opcion;
       this.href = href;
       this.orden = orden;
       this.visible = visible;
       this.descripcion = descripcion;
       this.nivel = nivel;
       this.opcionesIdOpcion = opcionesIdOpcion;
       this.identificador = identificador;
       this.tipo = tipo;
       this.icono = icono;
       this.rolesOpcioneses = rolesOpcioneses;
    }
   
    public Integer getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }
    public Modulos getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Modulos modulos) {
        this.modulos = modulos;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    public String getHref() {
        return this.href;
    }
    
    public void setHref(String href) {
        this.href = href;
    }
    public Short getOrden() {
        return this.orden;
    }
    
    public void setOrden(Short orden) {
        this.orden = orden;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Integer getOpcionesIdOpcion() {
        return this.opcionesIdOpcion;
    }
    
    public void setOpcionesIdOpcion(Integer opcionesIdOpcion) {
        this.opcionesIdOpcion = opcionesIdOpcion;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Set getRolesOpcioneses() {
        return this.rolesOpcioneses;
    }
    
    public void setRolesOpcioneses(Set rolesOpcioneses) {
        this.rolesOpcioneses = rolesOpcioneses;
    }




}


