package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * RolesOpcionesId generated by hbm2java
 */
public class RolesOpcionesId  implements java.io.Serializable {


     private int idRol;
     private int idOpcion;

    public RolesOpcionesId() {
    }

    public RolesOpcionesId(int idRol, int idOpcion) {
       this.idRol = idRol;
       this.idOpcion = idOpcion;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public int getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesOpcionesId) ) return false;
		 RolesOpcionesId castOther = ( RolesOpcionesId ) other; 
         
		 return (this.getIdRol()==castOther.getIdRol())
 && (this.getIdOpcion()==castOther.getIdOpcion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRol();
         result = 37 * result + this.getIdOpcion();
         return result;
   }   


}


