package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * RolesOpciones generated by hbm2java
 */
public class RolesOpciones  implements java.io.Serializable {


     private RolesOpcionesId id;
     private Opciones opciones;
     private Roles roles;

    public RolesOpciones() {
    }

    public RolesOpciones(RolesOpcionesId id, Opciones opciones, Roles roles) {
       this.id = id;
       this.opciones = opciones;
       this.roles = roles;
    }
   
    public RolesOpcionesId getId() {
        return this.id;
    }
    
    public void setId(RolesOpcionesId id) {
        this.id = id;
    }
    public Opciones getOpciones() {
        return this.opciones;
    }
    
    public void setOpciones(Opciones opciones) {
        this.opciones = opciones;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


