package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private Integer idServicio;
     private Servidores servidores;
     private String servicio;
     private String propiedad;
     private String valor;
     private String descripcion;
     private Boolean visible;
     private String tipo;
     private Boolean requerido;

    public Servicios() {
    }

	
    public Servicios(Servidores servidores, String servicio, String propiedad, String valor, String tipo) {
        this.servidores = servidores;
        this.servicio = servicio;
        this.propiedad = propiedad;
        this.valor = valor;
        this.tipo = tipo;
    }
    public Servicios(Servidores servidores, String servicio, String propiedad, String valor, String descripcion, Boolean visible, String tipo, Boolean requerido) {
       this.servidores = servidores;
       this.servicio = servicio;
       this.propiedad = propiedad;
       this.valor = valor;
       this.descripcion = descripcion;
       this.visible = visible;
       this.tipo = tipo;
       this.requerido = requerido;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public Servidores getServidores() {
        return this.servidores;
    }
    
    public void setServidores(Servidores servidores) {
        this.servidores = servidores;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }
    public String getPropiedad() {
        return this.propiedad;
    }
    
    public void setPropiedad(String propiedad) {
        this.propiedad = propiedad;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Boolean getRequerido() {
        return this.requerido;
    }
    
    public void setRequerido(Boolean requerido) {
        this.requerido = requerido;
    }




}


