package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * UsuariosEmpresasId generated by hbm2java
 */
public class UsuariosEmpresasId  implements java.io.Serializable {


     private int idEmpresa;
     private int idUsuario;

    public UsuariosEmpresasId() {
    }

    public UsuariosEmpresasId(int idEmpresa, int idUsuario) {
       this.idEmpresa = idEmpresa;
       this.idUsuario = idUsuario;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariosEmpresasId) ) return false;
		 UsuariosEmpresasId castOther = ( UsuariosEmpresasId ) other; 
         
		 return (this.getIdEmpresa()==castOther.getIdEmpresa())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpresa();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


