package com.iqtb.pojos.xsaCR;
// Generated 21/06/2023 02:28:55 PM by Hibernate Tools 4.3.1



/**
 * Xmls generated by hbm2java
 */
public class Xmls  implements java.io.Serializable {


     private Integer idXml;
     private DocumentosRecibidos documentosRecibidos;
     private String xmlSf;
     private String xmlCf;
     private String xmlTimbrado;

    public Xmls() {
    }

	
    public Xmls(DocumentosRecibidos documentosRecibidos) {
        this.documentosRecibidos = documentosRecibidos;
    }
    public Xmls(DocumentosRecibidos documentosRecibidos, String xmlSf, String xmlCf, String xmlTimbrado) {
       this.documentosRecibidos = documentosRecibidos;
       this.xmlSf = xmlSf;
       this.xmlCf = xmlCf;
       this.xmlTimbrado = xmlTimbrado;
    }
   
    public Integer getIdXml() {
        return this.idXml;
    }
    
    public void setIdXml(Integer idXml) {
        this.idXml = idXml;
    }
    public DocumentosRecibidos getDocumentosRecibidos() {
        return this.documentosRecibidos;
    }
    
    public void setDocumentosRecibidos(DocumentosRecibidos documentosRecibidos) {
        this.documentosRecibidos = documentosRecibidos;
    }
    public String getXmlSf() {
        return this.xmlSf;
    }
    
    public void setXmlSf(String xmlSf) {
        this.xmlSf = xmlSf;
    }
    public String getXmlCf() {
        return this.xmlCf;
    }
    
    public void setXmlCf(String xmlCf) {
        this.xmlCf = xmlCf;
    }
    public String getXmlTimbrado() {
        return this.xmlTimbrado;
    }
    
    public void setXmlTimbrado(String xmlTimbrado) {
        this.xmlTimbrado = xmlTimbrado;
    }




}


